"""empty message

Revision ID: 3b634512eda7
Revises: bfeaabab694d
Create Date: 2025-02-04 22:13:06.605052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b634512eda7'
down_revision: Union[str, None] = 'bfeaabab694d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'for_whom')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('for_whom', postgresql.ENUM('user', 'manufacturer', 'support_agent', 'admin', name='rank'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
